name: sign_in
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  platform: ^3.1.0
  cloud_firestore: ^2.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  get: ^4.3.8
  google_fonts: ^2.0.0
  google_sign_in: ^5.1.0
  sign_button: ^2.0.1
  camera: ^0.10.0+1           #for displaying the camera...
  video_player: ^2.4.7  #for displaying videos...  
  fl_chart: ^0.55.2   
  smooth_page_indicator: ^1.0.0+2  
  youtube_player_flutter: ^8.0.0   # play youtube videos

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
  uses-material-design: true
  
  assets:
    - assets/

  

  # fonts:
  # - family: Pacifico
  #   fonts:
  #   - asset: fonts/Pacifico-Regular.ttf

  # - family: Source Sans Pro
  #   fonts:
  #   - asset: fonts/SourceSansPro-Regular.ttf
 
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #     
        


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
